Q1

Yes, there is a difference in the data type of the variables list_ and array_list.

The data type of list_ is <class 'list'>, which means it is a Python list. Lists are mutable, meaning their elements can be changed after they are created.
The data type of array_list is object, which means it is a NumPy array of objects. NumPy arrays are immutable, meaning their elements cannot be changed after they are created. Additionally, NumPy arrays are more efficient for storing and manipulating numerical data than Python lists.

In [1]:
import numpy as np

# Create a list of strings
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array of strings
array_list = np.array(list_, dtype=object)

# Print the data types of both variables
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", array_list.dtype)


Data type of list_:  <class 'list'>
Data type of array_list:  object


In [3]:
#Q2
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(list_, dtype=object)

# Print the data types directly (no need to iterate through elements)
print("Data type of each element in list_: ", str(list_[0]).__class__)
print("Data type of each element in array_list: ", array_list.dtype)


Data type of each element in list_:  <class 'str'>
Data type of each element in array_list:  object


Q3
Yes, there will be a difference in the data type of the elements in list_ and array_list with the provided code:

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array with dtype=int
array_list = np.array(list_, dtype=int)

# Print the data types of elements
print("Data type of each element in list_: ", [type(x) for x in list_])
print("Data type of each element in array_list: ", array_list.dtype)


Data type of each element in list_:  [<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]
Data type of each element in array_list:  int64


In [5]:
#Q4
import numpy as np

# Create a list of lists
num_list = [[1, 2, 3], [4, 5, 6]]

# Convert the list to a NumPy array
num_array = np.array(num_list)

# Find the shape and size of the array
shape = num_array.shape
size = num_array.size

# Print the shape and size
print("Shape of num_array:", shape)
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [7]:
#Q5
import numpy as np

# Create a 3x3 zero matrix using np.zeros
zero_matrix = np.zeros(shape=(3, 3))

# Print the matrix
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Q6
import numpy as np

# Create a 5x5 identity matrix using np.eye
identity_matrix = np.eye(5)

# Print the matrix
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
